### ISSUE TITLE
Camera Pan Movement Limits

### ISSUE THREAD

**Issue by dstar64** [varnholt/deceptus_engine#91]
Camera Pan must move inside "rooms" layer limits

**Comment by Nikspace2** [comment]
And keep the player always in the screen.
And not be able to pan while moving.

Vertical pan of the camera is necessary for tall vertical areas to check below the player to see were they fall is safe.

But horizontal pan is creating issues on the feeling of the game. 
Player will be able to preview the area before moving forward.
I believe forcing the player to go the end of the room without previewing the area with just a pan,
will create the feeling of the explorer. What is in the end over there ?

Here is a comparison.
[video link](https://www.youtube.com/watch?v=UhMokWj3QZI)
